#!/bin/bash

packages=("qemu-kvm" "libvirt-daemon-system" "libvirt-clients" "bridge-utils" "ovmf" "virt-manager" "cockpit-machines")
total_packages=${#packages[@]}
progress=0

# Function to display a text-based progress indicator
function show_progress {
    package_name=$1
    percentage=$2
    echo "Installing $package_name: $percentage%"
}

# Function to check if a package is installed
function is_package_installed {
    dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "ok installed"
}

# Loop through each package and install if not already installed
for current_package in "${packages[@]}"; do
    if ! is_package_installed "$current_package"; then
        sudo apt-get install -y "$current_package" > /dev/null 2>&1
    fi

    ((progress++))
    percentage=$((progress * 100 / total_packages))
    show_progress "$current_package" $percentage
done

# Display completion message
echo "All packages installed successfully!"