#!/bin/bash

# Function to check if a package is installed
function is_package_installed {
    dpkg -l "$1" | grep -q "ii"
}

# Function to display a progress bar using pv
function install_package_with_progress {
    package_name=$1
    if is_package_installed "$package_name"; then
        echo "$package_name is already installed."
    else
        sudo apt-get install -y "$package_name" | pv -p -s $(apt-cache show "$package_name" | grep "Installed-Size:" | awk '{print $2}')k > /dev/null
    fi
}

# Install pv first
if is_package_installed "pv"; then
    echo "pv is already installed."
else
    sudo apt-get install -y "pv"
fi

# List of packages to install (excluding pv, as it's already installed)
packages=("nfs-kernel-server" "curl" "vim")

# Loop through each package and install if not already installed
for current_package in "${packages[@]}"; do
    install_package_with_progress "$current_package"
done

# Display completion message
echo "All packages installed successfully!"
