version: '3.8'
services:
  nginxpm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxpm
    hostname: ngixpm
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '82:81' # Admin Web Port
    volumes:
      - /home/miguelmariz/docker/npm/data:/data
      - /home/miguelmariz/docker/npm/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Europe/Lisbon
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s